name: "test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize" ]

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  changes:
    outputs:
      changes: ${{ steps.changed-dirs.outputs.all_modified_files }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
    - id: changed-dirs
      uses: tj-actions/changed-files@v46
      with:
        dir_names: true

  terraform:
    needs: [ changes ]
    if: ${{ needs.changes.outputs.changes && needs.changes.outputs.changes != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJSON(needs.changes.outputs.changes) }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    uses: marocchino/sticky-pull-request-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: ${{ matrix.dir.workdir }}
        message: |
          Test ${{ matrix.dir.workdir }} ended successfully.
