name: "test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize" ]

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  changes:
    outputs:
      paths: ${{ steps.changed-dirs.outputs.all_modified_files }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
    - id: changed-dirs
      uses: tj-actions/changed-files@v46
      with:
        dir_names: true

  tasks:
    needs: [ changes ]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.paths && needs.changes.outputs.paths != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        paths: ${{ fromJSON(needs.changes.outputs.paths) }}
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
    - uses: marocchino/sticky-pull-request-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: ${{ matrix.paths.workdir }}
        message: |
          Test ${{ matrix.paths.workdir }} ended successfully.
